### ISSUE TITLE
Thank you for building this!

### ISSUE THREAD

**Issue by ghost** [sjclemen/peten#1]
Hi I'm the creator of Mayan EDMS, thanks for building this uploader. I'm trying to build it but my system is not setup for Java development so if you could send me a screenshot I can post a link here http://www.mayan-edms.com/ecosystem/

Thanks again for building this, I look forward to having it running.

PS: the API bugs have been fixed in version 2.1, working on 2.1.1 right now.

**Comment by sjclemen** [comment]
![petenedmssubmit](https://cloud.githubusercontent.com/assets/8887030/15382326/49cce6b0-1d57-11e6-91c0-86a0822e9d5e.png)

Thanks for your interest! Unfortunately, as the readme states, it's not exactly straightforward to build or use right now. Now that a major barrier to getting it working for most people is resolved (no need patch Mayan), I'll look into cleaning the code's "portability" (read: hardcoded API string and assuming users have a particular index/metadata setup) and getting binary builds up. Thanks!

**Comment by ghost** [comment]
Done! http://www.mayan-edms.com/ecosystem/ hopefully this will drive users here and someone that might be able to help you. 

Don't hesitate to open an issue entry if you find more problem with the api (https://gitlab.com/mayan-edms/mayan-edms).

Thanks!

![screenshot from 2016-05-20 21-57-32](https://cloud.githubusercontent.com/assets/413955/15445815/d9355ffe-1eb4-11e6-9698-308841958222.png)

**Comment by sjclemen** [comment]
![bicubic-scaled-peten](https://cloud.githubusercontent.com/assets/8887030/15445988/1ae04206-1ede-11e6-93a3-7ae52d877bcf.png)
Hey @rosarior would you mind using this scaled version instead? It has the exact same dimensions, but the fonts/lines look way better. Thanks again for adding me to the ecosystem page.

**Comment by ghost** [comment]
Done. Thank you!

https://gitlab.com/mayan-edms/website/commit/0acdf316a1cddea1e77d37b73c1398d35c115ff1
